name: Build & Deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build-image:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build and publish a Docker image for ${{ github.repository }}
              uses: macbre/push-to-ghcr@master
              with:
                  image_name: jason-rietzke/octo-lamp
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  image_tag: latest
